export enum DEPTH {
    BACKGROUND_VERYLOW = 0,
    BACKGROUND_LOW,
    BACKGROUND_MEDIUM,
    BACKGROUND_HIGH,
    BACKGROUND_VERYHIGH,
    OBJECT_VERYLOW,
    OBJECT_LOW,
    OBJECT_MEDIUM,
    OBJECT_HIGH,
    OBJECT_VERYHIGH,
}
